FROM node:24-trixie-slim as node

FROM python:3.14-slim-trixie

RUN apt-get update && \
    apt-get install -y ca-certificates socat iproute2 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=node /usr/local/bin/node /usr/local/bin/node

WORKDIR /app
COPY packages/runner-agents/dist/bundle.mjs /app/bundle.mjs
COPY environments/entrypoint.sh /app/entrypoint.sh
