/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["describeInstance"];
  };
  "/actions": {
    put: operations["createSyncAction"];
  };
  "/balloon": {
    get: operations["describeBalloonConfig"];
    /** Creates a new balloon device if one does not already exist, otherwise updates it, before machine startup. This will fail after machine startup. Will fail if update is not possible. */
    put: operations["putBalloon"];
    /** Updates an existing balloon device, before or after machine startup. Will fail if update is not possible. */
    patch: operations["patchBalloon"];
  };
  "/balloon/statistics": {
    get: operations["describeBalloonStats"];
    /** Updates an existing balloon device statistics interval, before or after machine startup. Will fail if update is not possible. */
    patch: operations["patchBalloonStatsInterval"];
  };
  "/boot-source": {
    /** Creates new boot source if one does not already exist, otherwise updates it. Will fail if update is not possible. */
    put: operations["putGuestBootSource"];
  };
  "/cpu-config": {
    /** Provides configuration to the Firecracker process to specify vCPU resource configuration prior to launching the guest machine. */
    put: operations["putCpuConfiguration"];
  };
  "/drives/{drive_id}": {
    /** Creates new drive with ID specified by drive_id path parameter. If a drive with the specified ID already exists, updates its state based on new input. Will fail if update is not possible. */
    put: operations["putGuestDriveByID"];
    /** Updates the properties of the drive with the ID specified by drive_id path parameter. Will fail if update is not possible. */
    patch: operations["patchGuestDriveByID"];
  };
  "/logger": {
    put: operations["putLogger"];
  };
  "/machine-config": {
    /** Gets the machine configuration of the VM. When called before the PUT operation, it will return the default values for the vCPU count (=1), memory size (=128 MiB). By default SMT is disabled and there is no CPU Template. */
    get: operations["getMachineConfiguration"];
    /** Updates the Virtual Machine Configuration with the specified input. Firecracker starts with default values for vCPU count (=1) and memory size (=128 MiB). The vCPU count is restricted to the [1, 32] range. With SMT enabled, the vCPU count is required to be either 1 or an even number in the range. otherwise there are no restrictions regarding the vCPU count. If 2M hugetlbfs pages are specified, then `mem_size_mib` must be a multiple of 2. If any of the parameters has an incorrect value, the whole update fails. All parameters that are optional and are not specified are set to their default values (smt = false, track_dirty_pages = false, cpu_template = None, huge_pages = None). */
    put: operations["putMachineConfiguration"];
    /** Partially updates the Virtual Machine Configuration with the specified input. If any of the parameters has an incorrect value, the whole update fails. */
    patch: operations["patchMachineConfiguration"];
  };
  "/metrics": {
    put: operations["putMetrics"];
  };
  "/mmds": {
    get: operations["getMmds"];
    put: operations["putMmds"];
    patch: operations["patchMmds"];
  };
  "/mmds/config": {
    /** Configures MMDS version, IPv4 address used by the MMDS network stack and interfaces that allow MMDS requests. */
    put: operations["putMmdsConfig"];
  };
  "/entropy": {
    /** Enables an entropy device that provides high-quality random data to the guest. */
    put: operations["putEntropyDevice"];
  };
  "/network-interfaces/{iface_id}": {
    /** Creates new network interface with ID specified by iface_id path parameter. */
    put: operations["putGuestNetworkInterfaceByID"];
    /** Updates the rate limiters applied to a network interface. */
    patch: operations["patchGuestNetworkInterfaceByID"];
  };
  "/snapshot/create": {
    /** Creates a snapshot of the microVM state. The microVM should be in the `Paused` state. */
    put: operations["createSnapshot"];
  };
  "/snapshot/load": {
    /** Loads the microVM state from a snapshot. Only accepted on a fresh Firecracker process (before configuring any resource other than the Logger and Metrics). */
    put: operations["loadSnapshot"];
  };
  "/version": {
    get: operations["getFirecrackerVersion"];
  };
  "/vm": {
    /** Sets the desired state (Paused or Resumed) for the microVM. */
    patch: operations["patchVm"];
  };
  "/vm/config": {
    /** Gets configuration for all VM resources. If the VM is restored from a snapshot, the boot-source, machine-config.smt and machine-config.cpu_template will be empty. */
    get: operations["getExportVmConfig"];
  };
  "/vsock": {
    /** The first call creates the device with the configuration specified in body. Subsequent calls will update the device configuration. May fail if update is not possible. */
    put: operations["putGuestVsock"];
  };
}

export interface definitions {
  /** @description Balloon device descriptor. */
  Balloon: {
    /** @description Target balloon size in MiB. */
    amount_mib: number;
    /** @description Whether the balloon should deflate when the guest has memory pressure. */
    deflate_on_oom: boolean;
    /** @description Interval in seconds between refreshing statistics. A non-zero value will enable the statistics. Defaults to 0. */
    stats_polling_interval_s?: number;
  };
  /** @description Balloon device descriptor. */
  BalloonUpdate: {
    /** @description Target balloon size in MiB. */
    amount_mib: number;
  };
  /** @description Describes the balloon device statistics. */
  BalloonStats: {
    /** @description Target number of pages the device aims to hold. */
    target_pages: number;
    /** @description Actual number of pages the device is holding. */
    actual_pages: number;
    /** @description Target amount of memory (in MiB) the device aims to hold. */
    target_mib: number;
    /** @description Actual amount of memory (in MiB) the device is holding. */
    actual_mib: number;
    /**
     * Format: int64
     * @description The amount of memory that has been swapped in (in bytes).
     */
    swap_in?: number;
    /**
     * Format: int64
     * @description The amount of memory that has been swapped out to disk (in bytes).
     */
    swap_out?: number;
    /**
     * Format: int64
     * @description The number of major page faults that have occurred.
     */
    major_faults?: number;
    /**
     * Format: int64
     * @description The number of minor page faults that have occurred.
     */
    minor_faults?: number;
    /**
     * Format: int64
     * @description The amount of memory not being used for any purpose (in bytes).
     */
    free_memory?: number;
    /**
     * Format: int64
     * @description The total amount of memory available (in bytes).
     */
    total_memory?: number;
    /**
     * Format: int64
     * @description An estimate of how much memory is available (in bytes) for starting new applications, without pushing the system to swap.
     */
    available_memory?: number;
    /**
     * Format: int64
     * @description The amount of memory, in bytes, that can be quickly reclaimed without additional I/O. Typically these pages are used for caching files from disk.
     */
    disk_caches?: number;
    /**
     * Format: int64
     * @description The number of successful hugetlb page allocations in the guest.
     */
    hugetlb_allocations?: number;
    /**
     * Format: int64
     * @description The number of failed hugetlb page allocations in the guest.
     */
    hugetlb_failures?: number;
  };
  /** @description Update the statistics polling interval, with the first statistics update scheduled immediately. Statistics cannot be turned on/off after boot. */
  BalloonStatsUpdate: {
    /** @description Interval in seconds between refreshing statistics. */
    stats_polling_interval_s: number;
  };
  /** @description Boot source descriptor. */
  BootSource: {
    /** @description Kernel boot arguments */
    boot_args?: string;
    /** @description Host level path to the initrd image used to boot the guest */
    initrd_path?: string;
    /** @description Host level path to the kernel image used to boot the guest */
    kernel_image_path: string;
  };
  /**
   * @description The CPU Template defines a set of flags to be disabled from the microvm so that the features exposed to the guest are the same as in the selected instance type. This parameter has been deprecated and it will be removed in future Firecracker release.
   * @default None
   * @enum {string}
   */
  CpuTemplate: "C3" | "T2" | "T2S" | "T2CL" | "T2A" | "V1N1" | "None";
  /** @description The CPU configuration template defines a set of bit maps as modifiers of flags accessed by register to be disabled/enabled for the microvm. */
  CpuConfig: {
    /** @description A collection of CPUIDs to be modified. (x86_64) */
    cpuid_modifiers?: { [key: string]: unknown };
    /** @description A collection of model specific registers to be modified. (x86_64) */
    msr_modifiers?: { [key: string]: unknown };
    /** @description A collection of registers to be modified. (aarch64) */
    reg_modifiers?: { [key: string]: unknown };
    /** @description A collection of vcpu features to be modified. (aarch64) */
    vcpu_features?: { [key: string]: unknown };
    /** @description A collection of kvm capabilities to be modified. (aarch64) */
    kvm_capabilities?: { [key: string]: unknown };
  };
  Drive: {
    drive_id: string;
    /** @description Represents the unique id of the boot partition of this device. It is optional and it will be taken into account only if the is_root_device field is true. */
    partuuid?: string;
    is_root_device: boolean;
    /**
     * @description Represents the caching strategy for the block device.
     * @default Unsafe
     * @enum {string}
     */
    cache_type?: "Unsafe" | "Writeback";
    /** @description Is block read only. This field is required for virtio-block config and should be omitted for vhost-user-block configuration. */
    is_read_only?: boolean;
    /** @description Host level path for the guest drive. This field is required for virtio-block config and should be omitted for vhost-user-block configuration. */
    path_on_host?: string;
    rate_limiter?: definitions["RateLimiter"];
    /**
     * @description Type of the IO engine used by the device. "Async" is supported on host kernels newer than 5.10.51. This field is optional for virtio-block config and should be omitted for vhost-user-block configuration.
     * @default Sync
     * @enum {string}
     */
    io_engine?: "Sync" | "Async";
    /** @description Path to the socket of vhost-user-block backend. This field is required for vhost-user-block config should be omitted for virtio-block configuration. */
    socket?: string;
  };
  Error: {
    /** @description A description of the error condition */
    fault_message?: string;
  };
  FullVmConfiguration: {
    balloon?: definitions["Balloon"];
    /** @description Configurations for all block devices. */
    drives?: definitions["Drive"][];
    "boot-source"?: definitions["BootSource"];
    "cpu-config"?: definitions["CpuConfig"];
    logger?: definitions["Logger"];
    "machine-config"?: definitions["MachineConfiguration"];
    metrics?: definitions["Metrics"];
    "mmds-config"?: definitions["MmdsConfig"];
    /** @description Configurations for all net devices. */
    "network-interfaces"?: definitions["NetworkInterface"][];
    vsock?: definitions["Vsock"];
    entropy?: definitions["EntropyDevice"];
  };
  /** @description Variant wrapper containing the real action. */
  InstanceActionInfo: {
    /**
     * @description Enumeration indicating what type of action is contained in the payload
     * @enum {string}
     */
    action_type: "FlushMetrics" | "InstanceStart" | "SendCtrlAltDel";
  };
  /** @description Describes MicroVM instance information. */
  InstanceInfo: {
    /** @description Application name. */
    app_name: string;
    /** @description MicroVM / instance ID. */
    id: string;
    /**
     * @description The current detailed state (Not started, Running, Paused) of the Firecracker instance. This value is read-only for the control-plane.
     * @enum {string}
     */
    state: "Not started" | "Running" | "Paused";
    /** @description MicroVM hypervisor build version. */
    vmm_version: string;
  };
  /** @description Describes the configuration option for the logging capability. */
  Logger: {
    /**
     * @description Set the level. The possible values are case-insensitive.
     * @default Info
     * @enum {string}
     */
    level?: "Error" | "Warning" | "Info" | "Debug" | "Trace" | "Off";
    /** @description Path to the named pipe or file for the human readable log output. */
    log_path?: string;
    /**
     * @description Whether or not to output the level in the logs.
     * @default false
     */
    show_level?: boolean;
    /**
     * @description Whether or not to include the file path and line number of the log's origin.
     * @default false
     */
    show_log_origin?: boolean;
    /**
     * @description The module path to filter log messages by.
     * @example api_server::request
     */
    module?: string;
  };
  /** @description Describes the number of vCPUs, memory size, SMT capabilities, huge page configuration and the CPU template. */
  MachineConfiguration: {
    cpu_template?: definitions["CpuTemplate"];
    /**
     * @description Flag for enabling/disabling simultaneous multithreading. Can be enabled only on x86.
     * @default false
     */
    smt?: boolean;
    /** @description Memory size of VM */
    mem_size_mib: number;
    /**
     * @description Enable dirty page tracking. If this is enabled, then incremental guest memory snapshots can be created. These belong to diff snapshots, which contain, besides the microVM state, only the memory dirtied since a previous snapshot. Full snapshots each contain a full copy of the guest memory.
     * @default false
     */
    track_dirty_pages?: boolean;
    /** @description Number of vCPUs (either 1 or an even number) */
    vcpu_count: number;
    /**
     * @description Which huge pages configuration (if any) should be used to back guest memory.
     * @enum {string}
     */
    huge_pages?: "None" | "2M";
  };
  MemoryBackend: {
    /** @enum {string} */
    backend_type: "File" | "Uffd";
    /** @description Based on 'backend_type' it is either 1) Path to the file that contains the guest memory to be loaded 2) Path to the UDS where a process is listening for a UFFD initialization control payload and open file descriptor that it can use to serve this process's guest memory page faults */
    backend_path: string;
  };
  /** @description Describes the configuration option for the metrics capability. */
  Metrics: {
    /** @description Path to the named pipe or file where the JSON-formatted metrics are flushed. */
    metrics_path: string;
  };
  /** @description Defines the MMDS configuration. */
  MmdsConfig: {
    /**
     * @description Enumeration indicating the MMDS version to be configured.
     * @default V1
     * @enum {string}
     */
    version?: "V1" | "V2";
    /** @description List of the network interface IDs capable of forwarding packets to the MMDS. Network interface IDs mentioned must be valid at the time of this request. The net device model will reply to HTTP GET requests sent to the MMDS address via the interfaces mentioned. In this case, both ARP requests and TCP segments heading to `ipv4_address` are intercepted by the device model, and do not reach the associated TAP device. */
    network_interfaces: string[];
    /**
     * Format: 169.254.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-4]).([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])
     * @description A valid IPv4 link-local address.
     * @default 169.254.169.254
     */
    ipv4_address?: string;
    /**
     * @description MMDS operates compatibly with EC2 IMDS (i.e. responds "text/plain" content regardless of Accept header in requests).
     * @default false
     */
    imds_compat?: boolean;
  };
  /** @description Describes the contents of MMDS in JSON format. */
  MmdsContentsObject: { [key: string]: unknown };
  /** @description Defines a network interface. */
  NetworkInterface: {
    guest_mac?: string;
    /** @description Host level path for the guest network interface */
    host_dev_name: string;
    iface_id: string;
    rx_rate_limiter?: definitions["RateLimiter"];
    tx_rate_limiter?: definitions["RateLimiter"];
  };
  PartialDrive: {
    drive_id: string;
    /** @description Host level path for the guest drive. This field is optional for virtio-block config and should be omitted for vhost-user-block configuration. */
    path_on_host?: string;
    rate_limiter?: definitions["RateLimiter"];
  };
  /** @description Defines a partial network interface structure, used to update the rate limiters for that interface, after microvm start. */
  PartialNetworkInterface: {
    iface_id: string;
    rx_rate_limiter?: definitions["RateLimiter"];
    tx_rate_limiter?: definitions["RateLimiter"];
  };
  /** @description Defines an IO rate limiter with independent bytes/s and ops/s limits. Limits are defined by configuring each of the _bandwidth_ and _ops_ token buckets. This field is optional for virtio-block config and should be omitted for vhost-user-block configuration. */
  RateLimiter: {
    /** @description Token bucket with bytes as tokens */
    bandwidth?: definitions["TokenBucket"];
    /** @description Token bucket with operations as tokens */
    ops?: definitions["TokenBucket"];
  };
  SnapshotCreateParams: {
    /** @description Path to the file that will contain the guest memory. */
    mem_file_path: string;
    /** @description Path to the file that will contain the microVM state. */
    snapshot_path: string;
    /**
     * @description Type of snapshot to create. It is optional and by default, a full snapshot is created.
     * @enum {string}
     */
    snapshot_type?: "Full" | "Diff";
  };
  /** @description Allows for changing the backing TAP device of a network interface during snapshot restore. */
  NetworkOverride: {
    /** @description The name of the interface to modify */
    iface_id: string;
    /** @description The new host device of the interface */
    host_dev_name: string;
  };
  /** @description Defines the configuration used for handling snapshot resume. Exactly one of the two `mem_*` fields must be present in the body of the request. */
  SnapshotLoadParams: {
    /** @description (Deprecated) Enable dirty page tracking to improve space efficiency of diff snapshots */
    enable_diff_snapshots?: boolean;
    /** @description Enable dirty page tracking to improve space efficiency of diff snapshots */
    track_dirty_pages?: boolean;
    /** @description Path to the file that contains the guest memory to be loaded. It is only allowed if `mem_backend` is not present. This parameter has been deprecated and it will be removed in future Firecracker release. */
    mem_file_path?: string;
    /** @description Configuration for the backend that handles memory load. If this field is specified, `mem_file_path` is forbidden. Either `mem_backend` or `mem_file_path` must be present at a time. */
    mem_backend?: definitions["MemoryBackend"];
    /** @description Path to the file that contains the microVM state to be loaded. */
    snapshot_path: string;
    /** @description When set to true, the vm is also resumed if the snapshot load is successful. */
    resume_vm?: boolean;
    /** @description Network host device names to override */
    network_overrides?: definitions["NetworkOverride"][];
  };
  /** @description Defines a token bucket with a maximum capacity (size), an initial burst size (one_time_burst) and an interval for refilling purposes (refill_time). The refill-rate is derived from size and refill_time, and it is the constant rate at which the tokens replenish. The refill process only starts happening after the initial burst budget is consumed. Consumption from the token bucket is unbounded in speed which allows for bursts bound in size by the amount of tokens available. Once the token bucket is empty, consumption speed is bound by the refill_rate. */
  TokenBucket: {
    /**
     * Format: int64
     * @description The initial size of a token bucket.
     */
    one_time_burst?: number;
    /**
     * Format: int64
     * @description The amount of milliseconds it takes for the bucket to refill.
     */
    refill_time: number;
    /**
     * Format: int64
     * @description The total number of tokens this bucket can hold.
     */
    size: number;
  };
  /** @description Defines the microVM running state. It is especially useful in the snapshotting context. */
  Vm: {
    /** @enum {string} */
    state: "Paused" | "Resumed";
  };
  /** @description Defines an entropy device. */
  EntropyDevice: {
    rate_limiter?: definitions["RateLimiter"];
  };
  /** @description Describes the Firecracker version. */
  FirecrackerVersion: {
    /** @description Firecracker build version. */
    firecracker_version: string;
  };
  /** @description Defines a vsock device, backed by a set of Unix Domain Sockets, on the host side. For host-initiated connections, Firecracker will be listening on the Unix socket identified by the path `uds_path`. Firecracker will create this socket, bind and listen on it. Host-initiated connections will be performed by connection to this socket and issuing a connection forwarding request to the desired guest-side vsock port (i.e. `CONNECT 52\n`, to connect to port 52). For guest-initiated connections, Firecracker will expect host software to be bound and listening on Unix sockets at `uds_path_<PORT>`. E.g. "/path/to/host_vsock.sock_52" for port number 52. */
  Vsock: {
    /** @description Guest Vsock CID */
    guest_cid: number;
    /** @description Path to UNIX domain socket, used to proxy vsock connections. */
    uds_path: string;
    /** @description This parameter has been deprecated and it will be removed in future Firecracker release. */
    vsock_id?: string;
  };
}

export interface operations {
  describeInstance: {
    responses: {
      /** The instance information */
      200: {
        schema: definitions["InstanceInfo"];
      };
      /** Internal Server Error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  createSyncAction: {
    parameters: {
      body: {
        info: definitions["InstanceActionInfo"];
      };
    };
    responses: {
      /** The update was successful */
      204: never;
      /** The action cannot be executed due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal Server Error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  describeBalloonConfig: {
    responses: {
      /** The balloon device configuration */
      200: {
        schema: definitions["Balloon"];
      };
      /** Balloon device not configured. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal Server Error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Creates a new balloon device if one does not already exist, otherwise updates it, before machine startup. This will fail after machine startup. Will fail if update is not possible. */
  putBalloon: {
    parameters: {
      body: {
        /** Balloon properties */
        body: definitions["Balloon"];
      };
    };
    responses: {
      /** Balloon device created/updated */
      204: never;
      /** Balloon device cannot be created/updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Updates an existing balloon device, before or after machine startup. Will fail if update is not possible. */
  patchBalloon: {
    parameters: {
      body: {
        /** Balloon properties */
        body: definitions["BalloonUpdate"];
      };
    };
    responses: {
      /** Balloon device updated */
      204: never;
      /** Balloon device cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  describeBalloonStats: {
    responses: {
      /** The balloon device statistics */
      200: {
        schema: definitions["BalloonStats"];
      };
      /** The balloon device statistics were not enabled when the device was configured. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal Server Error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Updates an existing balloon device statistics interval, before or after machine startup. Will fail if update is not possible. */
  patchBalloonStatsInterval: {
    parameters: {
      body: {
        /** Balloon properties */
        body: definitions["BalloonStatsUpdate"];
      };
    };
    responses: {
      /** Balloon statistics interval updated */
      204: never;
      /** Balloon statistics interval cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Creates new boot source if one does not already exist, otherwise updates it. Will fail if update is not possible. */
  putGuestBootSource: {
    parameters: {
      body: {
        /** Guest boot source properties */
        body: definitions["BootSource"];
      };
    };
    responses: {
      /** Boot source created/updated */
      204: never;
      /** Boot source cannot be created due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Provides configuration to the Firecracker process to specify vCPU resource configuration prior to launching the guest machine. */
  putCpuConfiguration: {
    parameters: {
      body: {
        /** CPU configuration request */
        body?: definitions["CpuConfig"];
      };
    };
    responses: {
      /** CPU configuration set successfully */
      204: never;
      /** CPU configuration cannot be updated due to invalid input format */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Creates new drive with ID specified by drive_id path parameter. If a drive with the specified ID already exists, updates its state based on new input. Will fail if update is not possible. */
  putGuestDriveByID: {
    parameters: {
      path: {
        /** The id of the guest drive */
        drive_id: string;
      };
      body: {
        /** Guest drive properties */
        body: definitions["Drive"];
      };
    };
    responses: {
      /** Drive created/updated */
      204: never;
      /** Drive cannot be created/updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error. */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Updates the properties of the drive with the ID specified by drive_id path parameter. Will fail if update is not possible. */
  patchGuestDriveByID: {
    parameters: {
      path: {
        /** The id of the guest drive */
        drive_id: string;
      };
      body: {
        /** Guest drive properties */
        body: definitions["PartialDrive"];
      };
    };
    responses: {
      /** Drive updated */
      204: never;
      /** Drive cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error. */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  putLogger: {
    parameters: {
      body: {
        /** Logging system description */
        body: definitions["Logger"];
      };
    };
    responses: {
      /** Logger created. */
      204: never;
      /** Logger cannot be initialized due to bad input. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error. */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Gets the machine configuration of the VM. When called before the PUT operation, it will return the default values for the vCPU count (=1), memory size (=128 MiB). By default SMT is disabled and there is no CPU Template. */
  getMachineConfiguration: {
    responses: {
      /** OK */
      200: {
        schema: definitions["MachineConfiguration"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Updates the Virtual Machine Configuration with the specified input. Firecracker starts with default values for vCPU count (=1) and memory size (=128 MiB). The vCPU count is restricted to the [1, 32] range. With SMT enabled, the vCPU count is required to be either 1 or an even number in the range. otherwise there are no restrictions regarding the vCPU count. If 2M hugetlbfs pages are specified, then `mem_size_mib` must be a multiple of 2. If any of the parameters has an incorrect value, the whole update fails. All parameters that are optional and are not specified are set to their default values (smt = false, track_dirty_pages = false, cpu_template = None, huge_pages = None). */
  putMachineConfiguration: {
    parameters: {
      body: {
        /** Machine Configuration Parameters */
        body?: definitions["MachineConfiguration"];
      };
    };
    responses: {
      /** Machine Configuration created/updated */
      204: never;
      /** Machine Configuration cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Partially updates the Virtual Machine Configuration with the specified input. If any of the parameters has an incorrect value, the whole update fails. */
  patchMachineConfiguration: {
    parameters: {
      body: {
        /** A subset of Machine Configuration Parameters */
        body?: definitions["MachineConfiguration"];
      };
    };
    responses: {
      /** Machine Configuration created/updated */
      204: never;
      /** Machine Configuration cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  putMetrics: {
    parameters: {
      body: {
        /** Metrics system description */
        body: definitions["Metrics"];
      };
    };
    responses: {
      /** Metrics system created. */
      204: never;
      /** Metrics system cannot be initialized due to bad input request or metrics system already initialized. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error. */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  getMmds: {
    responses: {
      /** The MMDS data store JSON. */
      200: {
        schema: { [key: string]: unknown };
      };
      /** The MMDS data store content can not be found. */
      404: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  putMmds: {
    parameters: {
      body: {
        /** The MMDS data store as JSON. */
        body?: definitions["MmdsContentsObject"];
      };
    };
    responses: {
      /** MMDS data store created/updated. */
      204: never;
      /** MMDS data store cannot be created due to bad input. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  patchMmds: {
    parameters: {
      body: {
        /** The MMDS data store patch JSON. */
        body?: definitions["MmdsContentsObject"];
      };
    };
    responses: {
      /** MMDS data store updated. */
      204: never;
      /** MMDS data store cannot be updated due to bad input. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Configures MMDS version, IPv4 address used by the MMDS network stack and interfaces that allow MMDS requests. */
  putMmdsConfig: {
    parameters: {
      body: {
        /** The MMDS configuration as JSON. */
        body: definitions["MmdsConfig"];
      };
    };
    responses: {
      /** MMDS configuration was created/updated. */
      204: never;
      /** MMDS configuration cannot be updated due to bad input. */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Enables an entropy device that provides high-quality random data to the guest. */
  putEntropyDevice: {
    parameters: {
      body: {
        /** Guest entropy device properties */
        body: definitions["EntropyDevice"];
      };
    };
    responses: {
      /** Entropy device created */
      204: never;
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Creates new network interface with ID specified by iface_id path parameter. */
  putGuestNetworkInterfaceByID: {
    parameters: {
      path: {
        /** The id of the guest network interface */
        iface_id: string;
      };
      body: {
        /** Guest network interface properties */
        body: definitions["NetworkInterface"];
      };
    };
    responses: {
      /** Network interface created/updated */
      204: never;
      /** Network interface cannot be created due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Updates the rate limiters applied to a network interface. */
  patchGuestNetworkInterfaceByID: {
    parameters: {
      path: {
        /** The id of the guest network interface */
        iface_id: string;
      };
      body: {
        /** A subset of the guest network interface properties */
        body: definitions["PartialNetworkInterface"];
      };
    };
    responses: {
      /** Network interface updated */
      204: never;
      /** Network interface cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Creates a snapshot of the microVM state. The microVM should be in the `Paused` state. */
  createSnapshot: {
    parameters: {
      body: {
        /** The configuration used for creating a snapshot. */
        body: definitions["SnapshotCreateParams"];
      };
    };
    responses: {
      /** Snapshot created */
      204: never;
      /** Snapshot cannot be created due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Loads the microVM state from a snapshot. Only accepted on a fresh Firecracker process (before configuring any resource other than the Logger and Metrics). */
  loadSnapshot: {
    parameters: {
      body: {
        /** The configuration used for loading a snapshot. */
        body: definitions["SnapshotLoadParams"];
      };
    };
    responses: {
      /** Snapshot loaded */
      204: never;
      /** Snapshot cannot be loaded due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  getFirecrackerVersion: {
    responses: {
      /** OK */
      200: {
        schema: definitions["FirecrackerVersion"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Sets the desired state (Paused or Resumed) for the microVM. */
  patchVm: {
    parameters: {
      body: {
        /** The microVM state */
        body: definitions["Vm"];
      };
    };
    responses: {
      /** Vm state updated */
      204: never;
      /** Vm state cannot be updated due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** Gets configuration for all VM resources. If the VM is restored from a snapshot, the boot-source, machine-config.smt and machine-config.cpu_template will be empty. */
  getExportVmConfig: {
    responses: {
      /** OK */
      200: {
        schema: definitions["FullVmConfiguration"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
  /** The first call creates the device with the configuration specified in body. Subsequent calls will update the device configuration. May fail if update is not possible. */
  putGuestVsock: {
    parameters: {
      body: {
        /** Guest vsock properties */
        body: definitions["Vsock"];
      };
    };
    responses: {
      /** Vsock created/updated */
      204: never;
      /** Vsock cannot be created due to bad input */
      400: {
        schema: definitions["Error"];
      };
      /** Internal server error */
      default: {
        schema: definitions["Error"];
      };
    };
  };
}

export interface external {}
